### ISSUE TITLE
Error when make

### ISSUE THREAD

**Issue by HuiSF** [lvzixun/clang-complete#4]
I meet an error when make cc lib. I don't know about -lclang, which path should use please?

ld: library not found for -lclang
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [cc_lib] Error 1

**Comment by lvzixun** [comment]
check `libclang.dylib` file exists in `clang-complete/lib` directory.

**Comment by HuiSF** [comment]
Thanks. I copied this file to lib path and ran make and make install successfully :) 
I also ran make install and it created an alias in the package, but after I met another problem. 

reloading plugin Clang-Complete.cc
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Y/Library/Application Support/Sublime Text 3/Packages/Clang-Complete/cc.py", line 2, in <module>
    from cc.clang import CXUnsavedFile, CXCompletionChunkKind, CXCursorKind
ImportError: No module named 'cc'
reloading plugin Clang-Complete.clang
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Y/Library/Application Support/Sublime Text 3/Packages/Clang-Complete/clang.py", line 4, in <module>
    from cc.enum import Enum
ImportError: No module named 'cc'
reloading plugin Clang-Complete.clang_error
reloading plugin Clang-Complete.enum
reloading plugin Clang-Complete.st_cc
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Y/Library/Application Support/Sublime Text 3/Packages/Clang-Complete/st_cc.py", line 6, in <module>
    from cc.clang_error import *
ImportError: No module named 'cc'

**Comment by lvzixun** [comment]
rename `Clang-Complete` directory to `cc` at `/Users/Y/Library/Application Support/Sublime Text 3/Packages/` directory.

**Comment by HuiSF** [comment]
Thanks for your patience...

Never mind. I found it... I should save this file first and use the auto completion.

Thank you very much.

**Comment by lvzixun** [comment]
I fix python3 import path bug. (update release 0.1.3 )
this is not need rename `Clang-Complete` to `cc`, if you download plugin from package control. 
not need `make` and `make install`.
thank your issue. ;)

because clang require an existing file,  so will throw exception when create a sublime text `untitled` file and no save.

**Comment by HuiSF** [comment]
Thank YOU for the awesome plugin. I'm glad to see you update it often.

Also I have another question, does the auto completion only work for keyword and functions? Take a vector object, when I type ".", no vector member functions in the auto completion menu though...

**Comment by lvzixun** [comment]
[clang code completion](http://clang.llvm.org/doxygen/group__CINDEX__CODE__COMPLET.html) is based on syntax. If you want use STL, you could add include headfile`"-isystem", "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1"`, at cc.sublime-settings. ;)

**Comment by HuiSF** [comment]
Updated to the latest version. Everything looks good! Thank you.
