### ISSUE TITLE
Starting issue.

### ISSUE THREAD

**Issue by alexeyignatiev** [lvzixun/clang-complete#6]
Hi!
I have ST3 running on my Mac OS X 10.10. Tried to use your clang-sublime plugin. However, I got the following message when loading ST3 with it:

reloading plugin Clang-Complete.cc
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/aign/Library/Application Support/Sublime Text 3/Packages/Clang-Complete/cc.py", line 8, in <module>
    libcc = cdll.LoadLibrary('%s/lib/libcc.so' % current_path)
  File "./ctypes/__init__.py", line 431, in LoadLibrary
  File "./ctypes/**init**.py", line 353, in **init**
OSError: dlopen(/Users/aign/Library/Application Support/Sublime Text 3/Packages/Clang-Complete/lib/libcc.so, 6): Library not loaded: @rpath/libclang.dylib
  Referenced from: /Users/aign/Library/Application Support/Sublime Text 3/Packages/Clang-Complete/lib/libcc.so
  Reason: image not found
reloading plugin Clang-Complete.clang
reloading plugin Clang-Complete.clang_error
reloading plugin Clang-Complete.enum
reloading plugin Clang-Complete.st_cc
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 74, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/**init**.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/aign/Library/Application Support/Sublime Text 3/Packages/Clang-Complete/st_cc.py", line 7, in <module>
    from .cc import *
  File "/Users/aign/Library/Application Support/Sublime Text 3/Packages/Clang-Complete/cc.py", line 8, in <module>
    libcc = cdll.LoadLibrary('%s/lib/libcc.so' % current_path)
  File "./ctypes/__init__.py", line 431, in LoadLibrary
  File "./ctypes/**init**.py", line 353, in **init**
OSError: dlopen(/Users/aign/Library/Application Support/Sublime Text 3/Packages/Clang-Complete/lib/libcc.so, 6): Library not loaded: @rpath/libclang.dylib
  Referenced from: /Users/aign/Library/Application Support/Sublime Text 3/Packages/Clang-Complete/lib/libcc.so
  Reason: image not found

Is there a chance to make it work? And what is the reason for this failure? Thank you.

**Comment by lvzixun** [comment]
because `libcc.so`'s `-rpath` setting invalid,  so maybe install fail from `package control`.
I fix this bug in  release `0.1.7` version.
I suggest install plugin from git repository, if you want quick fix. ;)
command as follow:

```
$ git clone https://github.com/lvzixun/clang-complete.git
$ cd clang-complete
$ make
$ make install
```

**Comment by SolarSunrise** [comment]
I also had this problem when I was installing the plugin from Package Control. Manually installing it from git, like the Ivzixun posted above, fixed the problem.

**Comment by alexeyignatiev** [comment]
Thanks, guys! This also solved my issue. So package control does not update the plugin at the same time it is updated here on github?

**Comment by lvzixun** [comment]
`package_control_channel` of the config as follow:

``` .json
{
            "name": "Clang-Complete",
            "details": "https://github.com/lvzixun/clang-complete",
            "labels": ["Clang", "Completion", "C", "C++", "OC"],
            "releases": [
                {
                    "sublime_text": ">=3000",
                    "platforms": "osx",
                    "tags": true
                }
            ]
        },
```

`package control` will update from github.  I have seen the release `0.1.7` version is available.
